### PR TITLE
Switch to --wait helm flag to wait for deployment to become ready

### PR DESCRIPTION
**Pull request by msiegenthaler**
See https://github.com/kubernetes/helm/blob/master/docs/using_helm.md

Use "--wait" together with --timeout to achieve the same effect we had before.

### CODE REVIEW

**Comment by msiegenthaler** [comment]
will fix #6

**Comment by msiegenthaler** [comment]
wait until kubernetes/helm#2426 is fixed before merging that.

**Comment by TimJones** [comment]
kubernetes/helm#2426 is merged now, can we get a revision on this issue??

**Comment by msiegenthaler** [comment]
I've updated the branch to the current master and created a docker image tagged `wait-ready`. Still want to test it out a bit more before we switch over.

**Comment by msiegenthaler** [comment]
Hm, it does not seem to work for me. Does anybody have success with the `--wait-` in helm?

**Comment by codesuki** [comment]
We are using `--wait` without problems deploying redis, but we don't set a timeout.

**Comment by wendorf** [comment]
`--wait` is working for me with `--timeout`. 👍 on getting this merged in.

**Comment by msiegenthaler** [comment]
ok, let's get this merged, as some of you are already using it with success.

**Pull request merged**
