### PR TITLE
bug: compute tiller_namespace consistently

### LINKED ISSUE #122: pr115 breaks kubeconfig tiller_namespace
#115 breaks kubeconfig tiller namespace. It adds logic to `out` but in doing so clobbers the shared logic in `common.sh`.

https://github.com/linkyard/concourse-helm-resource/blob/master/assets/common.sh#L93

I think the resolution will be to add the file detection logic as a clause to the `if` block in common.sh and remove it from `out`. Also, grabbing `tiller_namespace` should be handled by common.sh.

### PR DESCRIPTION
**Pull request by hstenzel**
Fixes #122

Looks like I was slow to the draw on Helm 2.14.1, sorry about the noise.

### CODE REVIEW

**Comment by hstenzel** [comment]
@msiegenthaler Can you review please?

@Typositoire since this is related to #115 that you submitted, perhaps you want to take a look?

 --Harley

**Comment by Typositoire** [comment]
My bad didnt realized it was setup there

**Comment by Typositoire** [comment]
It does look good tho 👍

**Comment by hstenzel** [comment]
> My bad didnt realized it was setup there

No problem. I moved it in the feature I had just submitted; it's easy to see how something like that would be missed in a merge.

**Pull request merged**
