### PR TITLE
Check if tillernamespace is overwritten in params first.

### PR DESCRIPTION
**Pull request by Typositoire**
Basically let you have tiller configmap/secret in the same namespace as the release.

### CODE REVIEW

**Comment by Typositoire** [comment]
Oopsie hold on I fucked up. BRB.

**Comment by Typositoire** [comment]
@msiegenthaler pokey pokey :P ?

**Comment by msiegenthaler** [comment]
Can you do a rebase, the change regarding the dynamic kube config got it into a conflict state.

**Comment by Typositoire** [comment]
Hey all good sorry I totally forgot about this PR :p I'm going to rebase and poke you back

**Comment by Typositoire** [comment]
@msiegenthaler Done!

**Pull request merged**
