### PR TITLE
Add support for using Helm --set to set individual values

### PR DESCRIPTION
**Pull request by dan1el**
Wanted to be able to use helm --set key1=val1 for overriding settings from values.yaml. Useful when deploying from Concourse and you want to set the image version without having to edit the values.yaml file from a task.

Each key/value pair will be added to helm_cmd as '--set key=value', if there are more then one pair it will just chain --set.

The value can either be a string or a path to a file. For instance if your tracking the version using the semver resource you can pass the path to the fetched file and it will read the contents of it.

### CODE REVIEW

**Comment by msiegenthaler** [comment]
Hi, thank you so much for your PR, great idea and execution!

I do have a slight concern about the "magic" dual meaning of the values (file vs. string), I'm afraid that could lead to confusion if a file accidentally exists. But I totally understand the need to have both and it's basically the simplest and most elegant way to have it.

I think the alternative would be to have an `override_values` and `override_values_file` that get merged.. with `override_values` being of higher priority.

@jagregory you are also an active user, do you have an opinion regarding this?

**Comment by dan1el** [comment]
Yes I agree, it's not optimal that the value can be both a string or a file location. Splitting it into `overide_values` and `override_values_file` is an option. 

Could also do something like
```
override_values:
  key: value
  from_file:
    key: path
```

**Comment by msiegenthaler** [comment]
The we could also get a collision if a key (inside the helm chart) would be named 'from_file'.

Another proposal using arrays:
```
override_values:
- key: my-key
  value: some literal value
- key: another-key
   path: build-results/123.txt
```

Until now I like this the best. It's a bit more verbose if every value is a literal but easier to understand in all other cases.

**Comment by dan1el** [comment]
I like that one the best too. More verbose as you say, but easier to understand and read.

**Comment by msiegenthaler** [comment]
Great. It'd be great if you could update your PR, do you think that'll be possible?

**Comment by dan1el** [comment]
Updated the PR now

**Pull request merged**
